### ISSUE TITLE
Panic: index out of bounds

### ISSUE THREAD

**Issue by tomassedovic** [termhn/giftrogue#1]
Hey!

I've been playing this and got a panic at some point. This was on the first level (assuming there's more), I was in a room with a bunch of goblins and as I attacked one of them, the game stopped.

Looks like an index underflow or something to me:
```
thread 'main' panicked at 'index out of bounds: the len is 70 but the index is 18446744071562067985', /checkout/src/liballoc/vec.rs:1552:10
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at /checkout/src/libcore/panicking.rs:58
  10: giftrogue::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: __libc_start_main
  14: _start
```

I was playing this in the release mode, so the info's not great. Also, I'm not sure whether you actually want to fix this or if it's just a throwavay thing.

**Comment by tomassedovic** [comment]
Okay, in debug mode:

```
thread 'main' panicked at 'attempt to negate with overflow', /checkout/src/libcore/num/mod.rs:1136:17
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: core::num::<impl i32>::abs
             at /checkout/src/libcore/num/mod.rs:1136
  11: giftrogue::Entity::move_towards
             at src/main.rs:195
  12: giftrogue::Ai::take_turn
             at src/main.rs:136
  13: giftrogue::main
             at src/main.rs:568
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  15: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by fu5ha** [comment]
Huh. Thought I'd squashed that... I'll take a look again heh. I think it has something to do with attempting a `move_towards` when on top of the player... which in turn is caused by a bug that happens when a monster is trying to fight on top of another monster's corpse.

Honestly not planning on continuing developing this much, just threw it up 'cause why not and to show someone who wanted to see it haha. It's just one level--find the key, bring it back to the chest. The idea is that this little game would be played on a little Raspberry Pi with an LCD screen and game pad control visible through the side of a gift box and when you opened the chest in the game, it would open the chest in real life as well... unfortunately the power supply I got wasn't quite enough to power the solenoid I bought, so it ended up a bit buggy, but still cool.

Thanks for checking it out anyway!... Making this has inspired me to start working on another roguelike, that I actually plan on taking somewhere :D

**Comment by tomassedovic** [comment]
I love the idea, that's awesome!
